/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

type Five = string | number | boolean | { [k: string]: any };

export type Four = {};

/**
 * Value that failed validation
 */
type Value =
  | string
  | number
  | boolean
  | Four
  | Array<string | number | boolean | { [k: string]: any } | null>;

export type ConstraintValidation = {
  /**
   * List of validation error messages
   */
  messages: Array<string>;
  /**
   * Value that failed validation
   */
  value?:
    | string
    | number
    | boolean
    | Four
    | Array<string | number | boolean | { [k: string]: any } | null>
    | null
    | undefined;
};

/** @internal */
const Five$inboundSchema: z.ZodType<Five, z.ZodTypeDef, unknown> = z
  .union([z.string(), z.number(), z.boolean(), z.record(z.any())]);

function fiveFromJSON(
  jsonString: string,
): SafeParseResult<Five, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Five$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Five' from JSON`,
  );
}

/** @internal */
const Four$inboundSchema: z.ZodType<Four, z.ZodTypeDef, unknown> = z
  .object({});

function fourFromJSON(
  jsonString: string,
): SafeParseResult<Four, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Four$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Four' from JSON`,
  );
}

/** @internal */
const Value$inboundSchema: z.ZodType<Value, z.ZodTypeDef, unknown> = z
  .union([
    z.string(),
    z.number(),
    z.boolean(),
    z.lazy(() => Four$inboundSchema),
    z.array(
      z.nullable(
        z.union([z.string(), z.number(), z.boolean(), z.record(z.any())]),
      ),
    ),
  ]);

function valueFromJSON(
  jsonString: string,
): SafeParseResult<Value, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Value$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Value' from JSON`,
  );
}

/** @internal */
export const ConstraintValidation$inboundSchema: z.ZodType<
  ConstraintValidation,
  z.ZodTypeDef,
  unknown
> = z.object({
  messages: z.array(z.string()),
  value: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.lazy(() => Four$inboundSchema),
      z.array(
        z.nullable(
          z.union([z.string(), z.number(), z.boolean(), z.record(z.any())]),
        ),
      ),
    ]),
  ).optional(),
});

function constraintValidationFromJSON(
  jsonString: string,
): SafeParseResult<ConstraintValidation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConstraintValidation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConstraintValidation' from JSON`,
  );
}
