/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import type { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ChatRenderOutput,
  ChatRenderOutput$inboundSchema,
} from "./chatrenderoutput.js";
import {
  DigestRegularOutput,
  DigestRegularOutput$inboundSchema,
} from "./digestregularoutput.js";
import {
  EmailRenderOutput,
  EmailRenderOutput$inboundSchema,
} from "./emailrenderoutput.js";
import {
  InAppRenderOutput,
  InAppRenderOutput$inboundSchema,
} from "./inapprenderoutput.js";
import {
  PreviewPayloadDto,
  PreviewPayloadDto$inboundSchema,
} from "./previewpayloaddto.js";
import {
  PushRenderOutput,
  PushRenderOutput$inboundSchema,
} from "./pushrenderoutput.js";
import {
  SmsRenderOutput,
  SmsRenderOutput$inboundSchema,
} from "./smsrenderoutput.js";

const GeneratePreviewResponseDtoResult9Type = {
  Digest: "digest",
} as const;
type GeneratePreviewResponseDtoResult9Type = ClosedEnum<
  typeof GeneratePreviewResponseDtoResult9Type
>;

export type Nine = {
  type?: GeneratePreviewResponseDtoResult9Type | undefined;
  preview?: DigestRegularOutput | undefined;
};

const GeneratePreviewResponseDtoResult8Type = {
  Delay: "delay",
} as const;
type GeneratePreviewResponseDtoResult8Type = ClosedEnum<
  typeof GeneratePreviewResponseDtoResult8Type
>;

export type Eight = {
  type?: GeneratePreviewResponseDtoResult8Type | undefined;
  preview?: DigestRegularOutput | undefined;
};

const GeneratePreviewResponseDtoResult7Type = {
  Chat: "chat",
} as const;
type GeneratePreviewResponseDtoResult7Type = ClosedEnum<
  typeof GeneratePreviewResponseDtoResult7Type
>;

export type Seven = {
  type?: GeneratePreviewResponseDtoResult7Type | undefined;
  preview?: ChatRenderOutput | undefined;
};

const GeneratePreviewResponseDtoResult6Type = {
  Push: "push",
} as const;
type GeneratePreviewResponseDtoResult6Type = ClosedEnum<
  typeof GeneratePreviewResponseDtoResult6Type
>;

export type Six = {
  type?: GeneratePreviewResponseDtoResult6Type | undefined;
  preview?: PushRenderOutput | undefined;
};

const GeneratePreviewResponseDtoResult5Type = {
  Sms: "sms",
} as const;
type GeneratePreviewResponseDtoResult5Type = ClosedEnum<
  typeof GeneratePreviewResponseDtoResult5Type
>;

export type Result5 = {
  type?: GeneratePreviewResponseDtoResult5Type | undefined;
  preview?: SmsRenderOutput | undefined;
};

const GeneratePreviewResponseDtoResult4Type = {
  InApp: "in_app",
} as const;
type GeneratePreviewResponseDtoResult4Type = ClosedEnum<
  typeof GeneratePreviewResponseDtoResult4Type
>;

export type Result4 = {
  type?: GeneratePreviewResponseDtoResult4Type | undefined;
  preview?: InAppRenderOutput | undefined;
};

const GeneratePreviewResponseDtoResult3Type = {
  Email: "email",
} as const;
type GeneratePreviewResponseDtoResult3Type = ClosedEnum<
  typeof GeneratePreviewResponseDtoResult3Type
>;

export type Three = {
  type?: GeneratePreviewResponseDtoResult3Type | undefined;
  preview?: EmailRenderOutput | undefined;
};

const GeneratePreviewResponseDtoResultType = {
  Email: "email",
} as const;
type GeneratePreviewResponseDtoResultType = ClosedEnum<
  typeof GeneratePreviewResponseDtoResultType
>;

export type Result2 = {
  type?: GeneratePreviewResponseDtoResultType | undefined;
  preview?: EmailRenderOutput | undefined;
};

/**
 * Preview result
 */
type GeneratePreviewResponseDtoResult =
  | { [k: string]: any }
  | Result2
  | Three
  | Result4
  | Result5
  | Six
  | Seven
  | Eight
  | Nine;

export type GeneratePreviewResponseDto = {
  /**
   * Preview payload example
   */
  previewPayloadExample: PreviewPayloadDto;
  /**
   * The payload schema that was used to generate the preview payload example
   */
  schema?: { [k: string]: any } | null | undefined;
  /**
   * Preview result
   */
  result:
    | { [k: string]: any }
    | Result2
    | Three
    | Result4
    | Result5
    | Six
    | Seven
    | Eight
    | Nine;
};

/** @internal */
const GeneratePreviewResponseDtoResult9Type$inboundSchema:
  z.ZodNativeEnum<typeof GeneratePreviewResponseDtoResult9Type> = z.nativeEnum(
    GeneratePreviewResponseDtoResult9Type,
  );

/** @internal */
const Nine$inboundSchema: z.ZodType<Nine, z.ZodTypeDef, unknown> = z
  .object({
    type: GeneratePreviewResponseDtoResult9Type$inboundSchema.optional(),
    preview: DigestRegularOutput$inboundSchema.optional(),
  });

function nineFromJSON(
  jsonString: string,
): SafeParseResult<Nine, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Nine$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Nine' from JSON`,
  );
}

/** @internal */
const GeneratePreviewResponseDtoResult8Type$inboundSchema:
  z.ZodNativeEnum<typeof GeneratePreviewResponseDtoResult8Type> = z.nativeEnum(
    GeneratePreviewResponseDtoResult8Type,
  );

/** @internal */
const Eight$inboundSchema: z.ZodType<Eight, z.ZodTypeDef, unknown> = z
  .object({
    type: GeneratePreviewResponseDtoResult8Type$inboundSchema.optional(),
    preview: DigestRegularOutput$inboundSchema.optional(),
  });

function eightFromJSON(
  jsonString: string,
): SafeParseResult<Eight, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Eight$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Eight' from JSON`,
  );
}

/** @internal */
const GeneratePreviewResponseDtoResult7Type$inboundSchema:
  z.ZodNativeEnum<typeof GeneratePreviewResponseDtoResult7Type> = z.nativeEnum(
    GeneratePreviewResponseDtoResult7Type,
  );

/** @internal */
const Seven$inboundSchema: z.ZodType<Seven, z.ZodTypeDef, unknown> = z
  .object({
    type: GeneratePreviewResponseDtoResult7Type$inboundSchema.optional(),
    preview: ChatRenderOutput$inboundSchema.optional(),
  });

function sevenFromJSON(
  jsonString: string,
): SafeParseResult<Seven, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Seven$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Seven' from JSON`,
  );
}

/** @internal */
const GeneratePreviewResponseDtoResult6Type$inboundSchema:
  z.ZodNativeEnum<typeof GeneratePreviewResponseDtoResult6Type> = z.nativeEnum(
    GeneratePreviewResponseDtoResult6Type,
  );

/** @internal */
const Six$inboundSchema: z.ZodType<Six, z.ZodTypeDef, unknown> = z
  .object({
    type: GeneratePreviewResponseDtoResult6Type$inboundSchema.optional(),
    preview: PushRenderOutput$inboundSchema.optional(),
  });

function sixFromJSON(
  jsonString: string,
): SafeParseResult<Six, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Six$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Six' from JSON`,
  );
}

/** @internal */
const GeneratePreviewResponseDtoResult5Type$inboundSchema:
  z.ZodNativeEnum<typeof GeneratePreviewResponseDtoResult5Type> = z.nativeEnum(
    GeneratePreviewResponseDtoResult5Type,
  );

/** @internal */
const Result5$inboundSchema: z.ZodType<Result5, z.ZodTypeDef, unknown> =
  z.object({
    type: GeneratePreviewResponseDtoResult5Type$inboundSchema.optional(),
    preview: SmsRenderOutput$inboundSchema.optional(),
  });

function result5FromJSON(
  jsonString: string,
): SafeParseResult<Result5, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Result5$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Result5' from JSON`,
  );
}

/** @internal */
const GeneratePreviewResponseDtoResult4Type$inboundSchema:
  z.ZodNativeEnum<typeof GeneratePreviewResponseDtoResult4Type> = z.nativeEnum(
    GeneratePreviewResponseDtoResult4Type,
  );

/** @internal */
const Result4$inboundSchema: z.ZodType<Result4, z.ZodTypeDef, unknown> =
  z.object({
    type: GeneratePreviewResponseDtoResult4Type$inboundSchema.optional(),
    preview: InAppRenderOutput$inboundSchema.optional(),
  });

function result4FromJSON(
  jsonString: string,
): SafeParseResult<Result4, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Result4$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Result4' from JSON`,
  );
}

/** @internal */
const GeneratePreviewResponseDtoResult3Type$inboundSchema:
  z.ZodNativeEnum<typeof GeneratePreviewResponseDtoResult3Type> = z.nativeEnum(
    GeneratePreviewResponseDtoResult3Type,
  );

/** @internal */
const Three$inboundSchema: z.ZodType<Three, z.ZodTypeDef, unknown> = z
  .object({
    type: GeneratePreviewResponseDtoResult3Type$inboundSchema.optional(),
    preview: EmailRenderOutput$inboundSchema.optional(),
  });

function threeFromJSON(
  jsonString: string,
): SafeParseResult<Three, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Three$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Three' from JSON`,
  );
}

/** @internal */
const GeneratePreviewResponseDtoResultType$inboundSchema:
  z.ZodNativeEnum<typeof GeneratePreviewResponseDtoResultType> = z.nativeEnum(
    GeneratePreviewResponseDtoResultType,
  );

/** @internal */
const Result2$inboundSchema: z.ZodType<Result2, z.ZodTypeDef, unknown> =
  z.object({
    type: GeneratePreviewResponseDtoResultType$inboundSchema.optional(),
    preview: EmailRenderOutput$inboundSchema.optional(),
  });

function result2FromJSON(
  jsonString: string,
): SafeParseResult<Result2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Result2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Result2' from JSON`,
  );
}

/** @internal */
const GeneratePreviewResponseDtoResult$inboundSchema: z.ZodType<
  GeneratePreviewResponseDtoResult,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.record(z.any()),
  z.lazy(() => Result2$inboundSchema),
  z.lazy(() => Three$inboundSchema),
  z.lazy(() => Result4$inboundSchema),
  z.lazy(() => Result5$inboundSchema),
  z.lazy(() => Six$inboundSchema),
  z.lazy(() => Seven$inboundSchema),
  z.lazy(() => Eight$inboundSchema),
  z.lazy(() => Nine$inboundSchema),
]);

function generatePreviewResponseDtoResultFromJSON(
  jsonString: string,
): SafeParseResult<GeneratePreviewResponseDtoResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeneratePreviewResponseDtoResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeneratePreviewResponseDtoResult' from JSON`,
  );
}

/** @internal */
export const GeneratePreviewResponseDto$inboundSchema: z.ZodType<
  GeneratePreviewResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  previewPayloadExample: PreviewPayloadDto$inboundSchema,
  schema: z.nullable(z.record(z.any())).optional(),
  result: z.union([
    z.record(z.any()),
    z.lazy(() => Result2$inboundSchema),
    z.lazy(() => Three$inboundSchema),
    z.lazy(() => Result4$inboundSchema),
    z.lazy(() => Result5$inboundSchema),
    z.lazy(() => Six$inboundSchema),
    z.lazy(() => Seven$inboundSchema),
    z.lazy(() => Eight$inboundSchema),
    z.lazy(() => Nine$inboundSchema),
  ]),
});

function generatePreviewResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<GeneratePreviewResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeneratePreviewResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeneratePreviewResponseDto' from JSON`,
  );
}
