/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type Security = {
  secretKey?: string | undefined;
  bearerAuth?: string | undefined;
};

/** @internal */
type Security$Outbound = {
  secretKey?: string | undefined;
  bearerAuth?: string | undefined;
};

/** @internal */
const Security$outboundSchema: z.ZodType<
  Security$Outbound,
  z.ZodTypeDef,
  Security
> = z.object({
  secretKey: z.string().optional(),
  bearerAuth: z.string().optional(),
});

function securityToJSON(security: Security): string {
  return JSON.stringify(Security$outboundSchema.parse(security));
}
