basePath: /
host: localhost:8081
info:
  contact: {}
  title: Go Fiber API
  version: 1.0.0
paths:
  /:
    get:
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Hello
  /alive:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Alive check
  /health:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health check
swagger: "2.0"
